# Generated by Django 4.0.8 on 2022-12-14 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration_minutes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_of_recording', models.DateField()),
                ('category', models.CharField(max_length=255)),
                ('current_status', models.CharField(max_length=255)),
                ('recording_url', models.CharField(max_length=500)),
                ('transcription_url', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
